name: Build Debug APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
    # --- Install core Linux utilities ---
    - name: Install core Linux utilities
      run: sudo apt-get update && sudo apt-get install -y tar unzip wget curl build-essential make

    # --- Checkout repository ---
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- Set up JDK ---
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # --- Install Go ---
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    # --- Install Android SDK & NDK ---
    - name: Install Android SDK & NDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        ndk-version: 25.2.9519653
        components: platform-tools,build-tools-33.0.2

    # --- Build AndroidLibV2rayLite for multiple ABIs ---
    - name: Build AndroidLibV2rayLite
      run: |
        cd AndroidLibV2rayLite
        go install golang.org/x/mobile/cmd/gomobile@latest
        export PATH=$PATH:$HOME/go/bin
        gomobile init

        # Build for all target ABIs
        cd ..
        chmod +x buildjni.sh
        ./buildjni.sh
        
        mkdir -p app/libs

        # Copy AAR
        cp AndroidLibV2rayLite/bin/AndroidLibV2rayLite.aar app/libs/

        # Copy all .so files from each ABI
        ABIS=("armeabi-v7a" "arm64-v8a" "x86" "x86_64")
        for ABI in "${ABIS[@]}"; do
          if [ -d "AndroidLibV2rayLite/obj/local/$ABI" ]; then
            cp AndroidLibV2rayLite/obj/local/$ABI/*.so app/libs/ || true
          fi
        done

    # --- Build APK ---
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # --- Upload artifact ---
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: leapvpn-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
