name: Build Debug APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- Set up JDK ---
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # --- Install required tools ---
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Install Android SDK Command line tools
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        ndk-version: 25.2.9519653
        components: platform-tools,build-tools-33.0.2

    - name: Install Make & unzip
      run: sudo apt-get update && sudo apt-get install -y make unzip wget

    # --- Build AndroidLibV2rayLite ---
    - name: Build AndroidLibV2rayLite
      run: |
        cd AndroidLibV2rayLite
        # Initialize gomobile
        go install golang.org/x/mobile/cmd/gomobile@latest
        export PATH=$PATH:$HOME/go/bin
        gomobile init
        chmod +x buildjni.sh
        sh buildjni.sh
        # Copy generated .aar and .so files to app/libs
        mkdir -p ../app/libs
        cp ./bin/AndroidLibV2rayLite.aar ../app/libs/
        cp ./obj/local/armeabi-v7a/*.so ../app/libs/ || true
        cd ..

    # --- Build APK ---
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # --- Upload artifact ---
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: leapvpn-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
